### ISSUE TITLE
In pgbackup.sh should we use -mtime instead of -atime for find command?

### ISSUE THREAD

**Issue by Ostrovski** [lesovsky/uber-scripts#3]
I have a trouble with not removed outdated backups. When I started to debug it I realized that command:
`find /opt/pgbackup -maxdepth 1 -type d -atime +3 -name "db-*"` does not find anything. And when I changed `atime` to `mtime` everything worked well.

Also in this line `rm $BACKUPDIR/$backup_label` it seems that `/archive/` part is missed. Am I right?

**Comment by lesovsky** [comment]
clonepg.sh script is old and I recommend use pg_basebackup directly with new options like ```-c fast -X stream --write-recovery-conf```
Issue with -atime/-mtime can be checked with ```stat``` utility. See on access/modify timestamps of your backup files and than check that the timestamps are satisfying conditions of ```find``` utility.

**Comment by Ostrovski** [comment]
Thanks a lot. I'm going to try it next time.
